### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by voidref** [niw/HapticKey#33] opened 2019-11-15 21:13 UTC
When attempting to build an error occurs:

```
Baryon:HapticKey alan$ make bootstrap
scripts/pod install
/Users/alan/src/HapticKey/scripts/exec_with_gems: line 54: /Users/alan/src/HapticKey/.gems/bin/bundle: No such file or directory
Update gems dependencies...
/Users/alan/src/HapticKey/scripts/exec_with_gems: line 58: /Users/alan/src/HapticKey/.gems/bin/bundle: No such file or directory
Fail to bundle install.
make: *** [Pods/Manifest.lock] Error 1
```

**Comment by niw** [comment] 2019-11-15 21:15
@voidref Thank you for filing the bug, I think this is caused by Ruby version change on macOS 10.15. I will address this issue soon.

**Comment by voidref** [comment] 2019-11-15 21:15
Thank you! Much appreciated!

**Comment by niw** [comment] 2019-11-18 07:47
Fixed by a0e0e6a, tested on macOS 10.15.

**Closed by niw** 2019-11-18 07:47 UTC
Labels: bug

**Comment by voidref** [comment] 2019-11-18 09:08
Makefile made, but now error is:

> ld: framework not found Pods_HapticKey

**Comment by voidref** [comment] 2019-11-18 09:09
This happened during the make, seems odd for it to want to unlock my watch:

`2019-11-18 01:03:55.490 xcodebuild[13596:2475728]  DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fd76c1c61e0:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/DeviceSupport/6.1/DeveloperDiskImage.dmg'>', error=-402653158: Error Domain=com.apple.dtdevicekit Code=-402653158 "The device is passcode protected." UserInfo={NSLocalizedFailureReason=Please unlock your device and reattach. (0xE800001A)., com.apple.dtdevicekit.stacktrace=(
`

**Comment by voidref** [comment] 2019-11-18 09:11
I also noticed this error

```
RegisterExecutionPolicyException /Users/alan/src/HapticKey/build/Build/Intermediates.noindex/ArchiveIntermediates/HapticKey/InstallationBuildProductsLocation/Applications/HapticKey.app (in target 'HapticKey' from project 'HapticKey')
    cd /Users/alan/src/HapticKey
    builtin-RegisterExecutionPolicyException /Users/alan/src/HapticKey/build/Build/Intermediates.noindex/ArchiveIntermediates/HapticKey/InstallationBuildProductsLocation/Applications/HapticKey.app
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'HapticKey' from project 'HapticKey')

```

**Comment by voidref** [comment] 2019-11-18 09:12
This should be a new issue, I think, sorry!

**Comment by voidref** [comment] 2019-11-18 09:15
nuke and pave worked.

(delete and re-clone, re run make bootstrap, open xcworkspace. Now everything is fine!)
