### ISSUE TITLE
Add a feature to trigger haptic feedback as we slide a slider

### ISSUE THREAD

**Issue by andrewwilliam26** [niw/HapticKey#20] opened 2018-06-26 14:22 UTC
i notice that when sliding the volume/brightness slider theres is no haptic feedback. I think it would be nice if when we slide a slider we get a feedback. 

I hope this is possible! 
so far I've been enjoying this app

**Comment by jdtzmn** [comment] 2018-06-26 23:07
There is already an open issue for this feature (#18).

**Comment by niw** [comment] 2018-06-27 00:31
Yes, I think it’s a duplicate of #4 request. I'll close this. To implement that, it may require extra research around the private API behavior which may not be trivial.

**Closed by niw** 2018-06-27 00:31 UTC
